[versions]

# Gradle
gradle = "9.0.0"

# Spring
spring-boot = "4.0.2"
spring-cloud = "2025.1.1"
spring-dependency-management = "1.1.7"
dependency-updates = "0.53.0"

# Quality Tools
checkstyle = "10.23.0"
pmd = "7.12.0"
spotbugs = "6.4.8"


[libraries]
# Spring Boot
spring-oauth2-client = { module = "org.springframework.boot:spring-boot-starter-oauth2-client" }
spring-security = { module = "org.springframework.boot:spring-boot-starter-security" }
spring-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux" }
spring-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-gateway = { module = "org.springframework.cloud:spring-cloud-starter-gateway-server-webflux"}
spring-eureka-client = { module = "org.springframework.cloud:spring-cloud-starter-netflix-eureka-client" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
dependency-updates = { id = "com.github.ben-manes.versions", version.ref = "dependency-updates" }
spotbugs = { id = "com.github.spotbugs", version.ref = "spotbugs" }
